# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shane Boland dot com
email: shane@shaneboland.com
description: > # this means to ignore newlines until "baseurl:"
  Front-end web designer from Upstate New York. This is my website. Built with Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shaneboland.com" # the base hostname & protocol for your site
github_username:  shanetheboland
permalink: pretty
host: 0.0.0.0

# Build settings
markdown: kramdown

# Outputs a compressed (minified) file
sass:
  style: compressed

collections:
  - projects
  - writing
